import { sql } from "drizzle-orm";
import {
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { sections, subjects, topics } from "./knowledge";
import { tsvector } from "./types";

/** Where a note came from (Architecture §5.3, decision 7). Only `user` exists until the AI phases. */
export const noteOrigin = pgEnum("note_origin", ["user", "ai", "imported"]);

/**
 * Notes (Architecture §3, notes storage rule; §5.4): the editor's JSON is the
 * source of truth, and `content_text` is a plain-text copy derived from it on
 * the server for search and, later, embeddings and AI. `search_vector` is
 * generated by Postgres from the title and that text.
 */
export const notes = pgTable(
  "notes",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id").notNull(),
    subjectId: uuid("subject_id").notNull(),
    sectionId: uuid("section_id").references(() => sections.id, { onDelete: "set null" }),
    title: text("title").notNull().default(""),
    content: jsonb("content").notNull(),
    contentText: text("content_text").notNull().default(""),
    wordCount: integer("word_count").notNull().default(0),
    origin: noteOrigin("origin").notNull().default("user"),
    /** Goes up by one on every save; a save made against an older revision is refused. */
    revision: integer("revision").notNull().default(1),
    searchVector: tsvector("search_vector")
      .notNull()
      .generatedAlwaysAs(
        sql`setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(content_text, '')), 'B')`,
      ),
    /** Set when the note is in the trash; trashed notes are deleted for good after 30 days. */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("notes_workspace_id_id_key").on(t.workspaceId, t.id),
    foreignKey({
      name: "notes_subject_fk",
      columns: [t.workspaceId, t.subjectId],
      foreignColumns: [subjects.workspaceId, subjects.id],
    }).onDelete("cascade"),
    index("notes_subject_idx").on(t.workspaceId, t.subjectId, t.deletedAt, t.updatedAt),
    index("notes_search_idx").using("gin", t.searchVector),
    index("notes_title_trgm_idx").using("gin", sql`${t.title} gin_trgm_ops`),
    check("notes_revision_positive", sql`${t.revision} > 0`),
  ],
);

/** The topics a note covers, chosen by the student. */
export const noteTopics = pgTable(
  "note_topics",
  {
    workspaceId: uuid("workspace_id").notNull(),
    noteId: uuid("note_id").notNull(),
    topicId: uuid("topic_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.noteId, t.topicId] }),
    foreignKey({
      name: "note_topics_note_fk",
      columns: [t.workspaceId, t.noteId],
      foreignColumns: [notes.workspaceId, notes.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "note_topics_topic_fk",
      columns: [t.workspaceId, t.topicId],
      foreignColumns: [topics.workspaceId, topics.id],
    }).onDelete("cascade"),
    index("note_topics_topic_idx").on(t.workspaceId, t.topicId),
  ],
);
